version: '3'
services:
  chatgpt:
    image: pengzhile/pandora
    container_name: chatgpt
    ports:
      - 8899:8899
    environment:
      - PANDORA_CLOUD=cloud
      - PANDORA_SERVER=0.0.0.0:8899
